language: python

python:
  - "2.7"
#  - "3.5"

install:
  - conda update --yes conda
  - conda config --add channels soft-matter
  - conda create -n testenv --yes pip nose setuptools python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - pip install -r requirements.txt
  - pip install -e .
  - mkdir -p $HOME/.config/matplotlib
  - echo backend : Agg >> $HOME/.config/matplotlib/matplotlibrc
  
before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH
  
script:
  - nosetests --with-xunit --with-coverage --xunit-file=nosetests.xml --cover-package=oceanwaves --cover-xml --cover-xml-file=coverage.xml --cover-html --cover-html-dir=coverage